# Generated by Django 3.1.4 on 2022-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='formData',
            field=models.FileField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
