# Generated by Django 3.1.4 on 2022-05-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220527_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='formData',
            new_name='file',
        ),
    ]
