# Generated by Django 3.1.4 on 2022-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220527_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='third',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Gender', models.TextField(choices=['Male', 'Female'])),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Date of Birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
