# Generated by Django 3.1.4 on 2022-05-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_third'),
    ]

    operations = [
        migrations.DeleteModel(
            name='third',
        ),
        migrations.AddField(
            model_name='form',
            name='error_resp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
